#!/usr/bin/env bash
# Runs inside an ubuntu:<release> container. Creates the Ubuntu rootfs
# with debootstrap from ports.ubuntu.com, then installs the desktop
# set in a chroot.
set -euo pipefail
# shellcheck disable=SC1091  # container path, checked separately
source /rb/lib/common.sh

profile="/rb/profiles/$DISTRO/$RELEASE"
MIRROR="http://ports.ubuntu.com/ubuntu-ports"

export DEBIAN_FRONTEND=noninteractive
apt-get -qq update
apt-get -qq install -y debootstrap zstd ca-certificates curl gnupg >/dev/null

log "debootstrap $CODENAME from $MIRROR"
debootstrap --arch=arm64 --components=main,restricted,universe,multiverse \
  "$CODENAME" "$ROOTFS" "$MIRROR"

cat > "$ROOTFS/etc/apt/sources.list.d/ubuntu.sources" <<EOF
Types: deb
URIs: $MIRROR
Suites: $CODENAME $CODENAME-updates $CODENAME-security
Components: main restricted universe multiverse
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
EOF
rm -f "$ROOTFS/etc/apt/sources.list"

# firefox from Mozilla's official apt repository (the Ubuntu archive
# only ships a snap transition package, which cannot work in a
# preinstalled image without snap seeding)
install -d -m 0755 "$ROOTFS/etc/apt/keyrings"
curl -fsSL https://packages.mozilla.org/apt/repo-signing-key.gpg |
  gpg --dearmor -o "$ROOTFS/etc/apt/keyrings/packages.mozilla.org.gpg"
cat > "$ROOTFS/etc/apt/sources.list.d/mozilla.list" <<EOF
deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.gpg] https://packages.mozilla.org/apt mozilla main
EOF
printf 'Package: *\nPin: origin packages.mozilla.org\nPin-Priority: 1000\n' \
  > "$ROOTFS/etc/apt/preferences.d/mozilla"

# keep generic firmware and known-bloat packages out; a hard dependency
# on any of these fails the build (fail fast, no silent skip)
{
  echo "# generated by rootfs-builder from profiles/$DISTRO/$RELEASE/excludes.txt"
  while IFS= read -r pat; do
    printf 'Package: %s\nPin: release *\nPin-Priority: -1\n\n' "$pat"
  done < <(read_list "$profile/excludes.txt")
} > "$ROOTFS/etc/apt/preferences.d/99-rootfs-builder-excludes"

# chroot setup
mount -t proc proc "$ROOTFS/proc"
mount -t sysfs sys "$ROOTFS/sys"
# --rbind + rslave: container /dev has submounts (null, pts, ...) that a
# plain --bind would not carry, leaving a broken /dev in the chroot
mount --rbind /dev "$ROOTFS/dev"
mount --make-rslave "$ROOTFS/dev"
mount -t tmpfs tmpfs "$ROOTFS/run"
rm -f "$ROOTFS/etc/resolv.conf"
cp /etc/resolv.conf "$ROOTFS/etc/resolv.conf"
printf '#!/bin/sh\nexit 101\n' > "$ROOTFS/usr/sbin/policy-rc.d"
chmod 755 "$ROOTFS/usr/sbin/policy-rc.d"
cleanup_chroot() {
  rm -f "$ROOTFS/usr/sbin/policy-rc.d"
  umount -l "$ROOTFS/dev" "$ROOTFS/proc" "$ROOTFS/sys" "$ROOTFS/run" 2>/dev/null || true
}
trap cleanup_chroot EXIT

mapfile -t base_pkgs    < <(read_list "$profile/base.txt")
mapfile -t desktop_pkgs < <(read_list "$profile/$DESKTOP.txt")

in_chroot apt-get -qq update
log "installing ${#base_pkgs[@]} base packages"
in_chroot apt-get install -y "${base_pkgs[@]}"

# Display manager selection (KDE): prefer Plasma Login Manager when the
# official archive provides it, else SDDM. GNOME always uses GDM
# (unit name detected: Ubuntu/Debian ship gdm3).
DM="" FIRST_BOOT=""
dm_pkgs=()
if [[ "$DESKTOP" == "kde" ]]; then
  FIRST_BOOT=tty-user-wizard
  if in_chroot apt-cache show plasma-login-manager >/dev/null 2>&1; then
    dm_pkgs=(plasma-login-manager)
  else
    dm_pkgs=(sddm)
  fi
fi

log "installing ${#desktop_pkgs[@]} desktop packages"
in_chroot apt-get install -y "${desktop_pkgs[@]}" "${dm_pkgs[@]}"

if [[ "$DESKTOP" == "kde" ]]; then
  DM="$(find_unit plasma-login-manager sddm)" || die "no display manager unit found"
else
  FIRST_BOOT=gnome-initial-setup
  DM="$(find_unit gdm3 gdm)" || die "no gdm unit found"
fi

in_chroot apt-get clean

# systemd-resolved layout (standard on Ubuntu)
ln -sf ../run/systemd/resolve/stub-resolv.conf "$ROOTFS/etc/resolv.conf"

pkg_installed() {
  # -W alone also matches known-but-not-installed packages; check the
  # actual dpkg status
  dpkg-query --admindir="$ROOTFS/var/lib/dpkg" -W \
    -f '${db:Status-Status}\n' "$1" 2>/dev/null | grep -qx installed
}
write_package_inventory() {
  dpkg-query --admindir="$ROOTFS/var/lib/dpkg" -W \
    -f '${Package}\t${Version}\t${Architecture}\n' | sort > "$1"
}

postprocess_rootfs "$DM" "$FIRST_BOOT"
verify_rootfs "$DM" "$profile/excludes.txt"
cleanup_chroot
trap - EXIT
finalize_rootfs "$MIRROR" false \
  "ubuntu archive with updates/security is not snapshotted; exact versions in packages.txt"
