#!/usr/bin/env bash
# Runs inside a debian:trixie-slim container. Creates the Debian rootfs
# (trixie or sid) with mmdebstrap, then installs the desktop set in a
# chroot.
set -euo pipefail
# shellcheck disable=SC1091  # container path, checked separately
source /rb/lib/common.sh

profile="/rb/profiles/$DISTRO/$RELEASE"
MIRROR="${DEBIAN_MIRROR:-http://deb.debian.org/debian}"

export DEBIAN_FRONTEND=noninteractive
apt-get -qq update
apt-get -qq install -y mmdebstrap zstd ca-certificates >/dev/null

log "mmdebstrap $CODENAME from $MIRROR"
mmdebstrap --arch=arm64 --variant=important --components=main \
  "$CODENAME" "$ROOTFS" "$MIRROR"

if [[ "$CODENAME" == "sid" ]]; then
  printf 'deb %s sid main\n' "$MIRROR" > "$ROOTFS/etc/apt/sources.list"
else
  cat > "$ROOTFS/etc/apt/sources.list" <<EOF
deb $MIRROR $CODENAME main
deb $MIRROR $CODENAME-updates main
deb http://security.debian.org/debian-security $CODENAME-security main
EOF
fi

# keep generic firmware and known-bloat packages out; a hard dependency
# on any of these fails the build (fail fast, no silent skip)
{
  echo "# generated by rootfs-builder from profiles/$DISTRO/$RELEASE/excludes.txt"
  while IFS= read -r pat; do
    printf 'Package: %s\nPin: release *\nPin-Priority: -1\n\n' "$pat"
  done < <(read_list "$profile/excludes.txt")
} > "$ROOTFS/etc/apt/preferences.d/99-rootfs-builder-excludes"

# chroot setup
mount -t proc proc "$ROOTFS/proc"
mount -t sysfs sys "$ROOTFS/sys"
mount --bind /dev "$ROOTFS/dev"
mount --bind /dev/pts "$ROOTFS/dev/pts"
mount -t tmpfs tmpfs "$ROOTFS/run"
cp /etc/resolv.conf "$ROOTFS/etc/resolv.conf"
printf '#!/bin/sh\nexit 101\n' > "$ROOTFS/usr/sbin/policy-rc.d"
chmod 755 "$ROOTFS/usr/sbin/policy-rc.d"
cleanup_chroot() {
  rm -f "$ROOTFS/usr/sbin/policy-rc.d"
  umount -l "$ROOTFS/dev/pts" "$ROOTFS/dev" "$ROOTFS/proc" "$ROOTFS/sys" "$ROOTFS/run" 2>/dev/null || true
}
trap cleanup_chroot EXIT

mapfile -t base_pkgs    < <(read_list "$profile/base.txt")
mapfile -t desktop_pkgs < <(read_list "$profile/$DESKTOP.txt")

in_chroot apt-get -qq update
log "installing ${#base_pkgs[@]} base packages"
in_chroot apt-get install -y "${base_pkgs[@]}"

# Display manager selection (KDE): prefer Plasma Login Manager when the
# official archive provides it, else SDDM. GNOME uses GDM (gdm3).
DM="" FIRST_BOOT=""
dm_pkgs=()
if [[ "$DESKTOP" == "kde" ]]; then
  FIRST_BOOT=tty-user-wizard
  if in_chroot apt-cache show plasma-login-manager >/dev/null 2>&1; then
    dm_pkgs=(plasma-login-manager)
  else
    dm_pkgs=(sddm)
  fi
fi

log "installing ${#desktop_pkgs[@]} desktop packages"
in_chroot apt-get install -y "${desktop_pkgs[@]}" "${dm_pkgs[@]}"

if [[ "$DESKTOP" == "kde" ]]; then
  DM="$(find_unit plasma-login-manager sddm)" || die "no display manager unit found"
else
  FIRST_BOOT=gnome-initial-setup
  DM="$(find_unit gdm3 gdm)" || die "no gdm unit found"
fi

in_chroot apt-get clean

# NetworkManager manages /etc/resolv.conf directly on Debian
rm -f "$ROOTFS/etc/resolv.conf"

pkg_installed() {
  dpkg-query --admindir="$ROOTFS/var/lib/dpkg" -W "$1" >/dev/null 2>&1
}
write_package_inventory() {
  dpkg-query --admindir="$ROOTFS/var/lib/dpkg" -W \
    -f '${Package}\t${Version}\t${Architecture}\n' | sort > "$1"
}

postprocess_rootfs "$DM" "$FIRST_BOOT"
verify_rootfs "$DM" "$profile/excludes.txt"
cleanup_chroot
trap - EXIT

if [[ "$CODENAME" == "sid" ]]; then
  note="debian sid resolved live from $MIRROR on $(date -u +%Y-%m-%d); NOT fully reproducible unless DEBIAN_MIRROR points at a snapshot.debian.org URL; exact versions in packages.txt"
else
  note="debian $CODENAME with updates/security is not snapshotted; exact versions in packages.txt"
fi
finalize_rootfs "$MIRROR" false "$note"
